JB-12: Add branch push abort when fail

diff --git a/.github/workflows/valid_jira_check.yml b/.github/workflows/valid_jira_check.yml
--- a/.github/workflows/valid_jira_check.yml
+++ b/.github/workflows/valid_jira_check.yml
@@ -2,8 +2,8 @@ name: Check Branch and Commit Rules
 
 on:
   push:
-    branches:
-      - '*'
+    branches-ignore:
+      - 'master'
 
 jobs:
   check-branch-and-commit:
@@ -12,10 +12,15 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
+        with:
+          fetch-depth: 0  # Ensure we fetch all commits to check the commit message
+
+      - name: Extract Branch Name
+        id: extract_branch_name
+        run: echo "BRANCH_NAME=$(echo ${{ github.ref }} | awk -F'/' '{print $NF}')" >> $GITHUB_ENV
 
       - name: Check Branch Name
         run: |
-          BRANCH_NAME=$(echo "${{ github.ref }}" | awk -F'/' '{print $3}')
           if [[ ! "${BRANCH_NAME}" =~ ^(task|bug|story)/JB-[0-9]+-[a-zA-Z0-9-]+$ ]]; then
             echo "Invalid branch name. The format should be [jira_ticket_type]/JB-[number]-[some_description_may_contain_hyphen]."
             exit 1
@@ -28,3 +33,9 @@ jobs:
             echo "Invalid commit message. The format should be JB-[number]: [Some_description]."
             exit 1
           fi
+
+      - name: Block Push if Checks Fail
+        if: failure()
+        run: |
+          echo "Commit or branch name checks failed. Cancelling the push."
+          exit 1
